### ISSUE TITLE
TypeError issue

### ISSUE THREAD

**Issue by longquanzheng** [nose-devs/nose#1026]
Hey guys, 
I occasionally run into this issue:

ERROR: Failure: TypeError (Required argument 'name' (pos 1) not found)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/packages/Nose/Nose-1.x.x.5208.9201/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/nose/loader.py", line 525, in makeTest
    return self._makeTest(obj, parent)
  File "~/packages/Nose/Nose-1.x.x.5208.9201/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/nose/loader.py", line 584, in _makeTest
    return MethodTestCase(obj)
  File "~/packages/Nose/Nose-1.x.x.5208.9201/RHEL5_64/DEV.STD.PTHREAD/build/lib/python2.7/site-packages/nose/case.py", line 345, in __init__
    self.inst = self.cls()
TypeError: Required argument 'name' (pos 1) not found
```
Any idea what is going on?

**Comment by warut-vijit** [comment]
Before someone makes a PR, could you post a sample of some code that you saw cause this error. That would be helpful for determining whether the error is on your end or on nose's end.
