### ISSUE TITLE
collections.Callable has become collections.abc.Callable in python 3.10 +

### ISSUE THREAD

**Issue by akshaydse** [nose-devs/nose#1127]
collections.Callable that has been used in _set_tests has become collections.abc.Callable is simple change can run it higher versions of python 
As one instance you can find it 
in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:

**Comment by akshaydse** [comment]
It is easily solvable by just adding two lines in  nosetest bash file

Import collections.abc
collections.Callable= collections.abc.Callable

**Comment by douglasdcm** [comment]
I'm having the same issue in Python 3.11

python version
```
(venv311) douglas@douglas:~/repo/guara$ python -V
Python 3.11.9
```

execution
```
(venv311) douglas@douglas:~/repo/guara$ nosetests test_todo_nosetests.py
Traceback (most recent call last):
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'test_todo_nosetests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/douglas/repo/guara/venv311/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
             ^^^^^^^^^^
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/local/lib/python3.11/unittest/main.py", line 101, in __init__
    self.parseArgs(argv)
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/loader.py", line 232, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/loader.py", line 232, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/loader.py", line 426, in loadTestsFromName
    return suite([Failure(exc[0], exc[1], exc[2],
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/suite.py", line 423, in __call__
    tests = self.wrapTests(tests)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/douglas/repo/guara/venv311/lib/python3.11/site-packages/nose/suite.py", line 541, in wrapTests
    if isinstance(tests, collections.Callable) or isinstance(tests, unittest.TestSuite):
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'
(venv311) douglas@douglas:~/repo/guara$ python -V
Python 3.11.9
```

pip freeze
```
~/repo/guara$ pip freeze
nose==1.3.7

```
