### ISSUE TITLE
running tests from a direct subdirectory of root (e.g. /vagrant) fails with ImportError

### ISSUE THREAD

**Issue by nickolay** [nose-devs/nose#518]
nose fails to run tests under these circumstances on a unix-y system:
1) a project is located in a direct subdirectory of the root folder (e.g. `/vagrant`),
2) the top-level directory is a package (i.e. `/vagrant/__init__.py` exists)
3) nose is run from the '/vagrant' directory

Here's the nose output when it fails:

```
$ nosetests --debug=nose.importer
nose.importer: DEBUG: Add path /vagrant
nose.importer: DEBUG: Add path /
nose.importer: DEBUG: insert / into sys.path
nose.importer: DEBUG: Import vagrant from /vagrant
nose.importer: DEBUG: Add path /vagrant
nose.importer: DEBUG: Add path /
nose.importer: DEBUG: find module part vagrant (vagrant) in ['/vagrant']
E
======================================================================
ERROR: Failure: ImportError (No module named vagrant)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/kuma-venv/lib/python2.6/site-packages/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vagrant/kuma-venv/lib/python2.6/site-packages/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/kuma-venv/lib/python2.6/site-packages/nose/importer.py", line 71, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named vagrant
```

This happens because in https://github.com/nose-devs/nose/blob/886c5cb2fdb4b3e2e6685b7eb5757c471b8229b2/nose/importer.py#L26 `path_parts = path_parts[:-(len(name_parts))]` ends up being empty, and `dir_path` is an empty string instead of '/'.

This empty string is normalized to the _current_ directory (e.g. /vagrant instead of /), and find_module is called to look for 'vagrant' package in /vagrant directory, which fails.

Possible workarounds are:
- move the project folder further down in directory hierarchy
- run the tests from the root directory instead (so that the empty dir_path normalized to '/').

The following change fixes the problem, although it probably can't be used as is:

```
diff --git a/nose/importer.py b/nose/importer.py
index c971b79..ed2b486 100644
--- a/nose/importer.py
+++ b/nose/importer.py
@@ -36,6 +36,7 @@ class Importer(object):
         path_parts = path_parts[:-(len(name_parts))]
         dir_path = os.sep.join(path_parts)
         # then import fqname starting from that dir
+        if dir_path == "": dir_path = "/"
         return self.importFromDir(dir_path, fqname)                

     def importFromDir(self, dir, fqname):
```

I should probably note that the fix worked on Linux with python 2.6.5; on my Mac OS 10.7 system with various python versions (macports 2.6.8 and system 2.7.1) even the correct invocation (`imp.find_module('vagrant', ['/'])`) fails when run from `/vagrant`, but not when run from `/`.

You can use the following script to recreate the testcase environment:

```
mkdir /vagrant
cd /vagrant
touch __init__.py
echo "def test(): pass" > test.py
nosetests # fails
cd / && nosetests # passes
```

**Comment by jetheurer** [comment]
When I move to the root directory, I'm no longer able to import the folder I'd like to test.  Do I need to change my path or something?  Thanks!
