### ISSUE TITLE
ValueError: too many values to unpack when running tests with Data Driven decorator

### ISSUE THREAD

**Issue by dlai0001** [nose-devs/nose#745]
I have a few tests that have data driven decorator, 
https://github.com/txels/ddt

When passing in tuples as seed data for the test, the node test runner will hit an exception without writing any test results.

``` text
25-Oct-2013 17:10:07    Traceback (most recent call last):
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/bin/nosetests-2.7", line 8, in <module>
25-Oct-2013 17:10:07        load_entry_point('nose==1.3.0', 'console_scripts', 'nosetests-2.7')()
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/lib/python2.7/site-packages/nose/core.py", line 118, in __init__
25-Oct-2013 17:10:07        **extra_args)
25-Oct-2013 17:10:07      File "/usr/local/lib/python2.7/unittest/main.py", line 94, in __init__
25-Oct-2013 17:10:07        self.parseArgs(argv)
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/lib/python2.7/site-packages/nose/core.py", line 169, in parseArgs
25-Oct-2013 17:10:07        self.createTests()
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/lib/python2.7/site-packages/nose/core.py", line 183, in createTests
25-Oct-2013 17:10:07        self.test = self.testLoader.loadTestsFromNames(self.testNames)
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/lib/python2.7/site-packages/nose/loader.py", line 476, in loadTestsFromNames
25-Oct-2013 17:10:07        return unittest.TestLoader.loadTestsFromNames(self, names, module)
25-Oct-2013 17:10:07      File "/usr/local/lib/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
25-Oct-2013 17:10:07        suites = [self.loadTestsFromName(name, module) for name in names]
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/lib/python2.7/site-packages/nose/loader.py", line 373, in loadTestsFromName
25-Oct-2013 17:10:07        addr = TestAddress(name, workingDir=self.workingDir)
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/lib/python2.7/site-packages/nose/selector.py", line 226, in __init__
25-Oct-2013 17:10:07        self.filename, self.module, self.call = split_test_name(name)
25-Oct-2013 17:10:07      File "/usr/local/atlassian/bamboo/.virtualenvs/qawtf5/lib/python2.7/site-packages/nose/util.py", line 374, in split_test_name
25-Oct-2013 17:10:07        file_part, fn = tail.split(':')
25-Oct-2013 17:10:07    ValueError: too many values to unpack
```

**Comment by yoavram** [comment]
I have a different example that causes a similar error: when running a specific test but writing bad syntax I get this error:
```
[venv] D:\workspace\project\code>nosetests tests\test_cli.py:AnalysisTestCase:test_bad_data_file
Traceback (most recent call last):
  File "D:\workspace\project\code\venv\Scripts\nosetests-script.py", line 5, in <module>
    sys.exit(run_exit())
  File "D:\workspace\project\code\venv\lib\site-packages\nose\core.py", line 121, in __init__
    **extra_args)
  File "D:\workspace\project\code\venv\lib\unittest\main.py", line 94, in __init__
    self.parseArgs(argv)
  File "D:\workspace\project\code\venv\lib\site-packages\nose\core.py", line 179, in parseArgs
    self.createTests()
  File "D:\workspace\project\code\venv\lib\site-packages\nose\core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "D:\workspace\project\code\venv\lib\site-packages\nose\loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "D:\workspace\project\code\venv\lib\unittest\loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "D:\workspace\project\code\venv\lib\site-packages\nose\loader.py", line 378, in loadTestsFromName
    addr = TestAddress(name, workingDir=self.workingDir)
  File "D:\workspace\project\code\venv\lib\site-packages\nose\selector.py", line 226, in __init__
    self.filename, self.module, self.call = split_test_name(name)
  File "D:\workspace\project\code\venv\lib\site-packages\nose\util.py", line 375, in split_test_name
    file_part, fn = tail.split(':')
ValueError: too many values to unpack
```
The syntax to nosetests is incorrect: `nosetests tests\test_cli.py:AnalysisTestCase:test_bad_data_file` - it should have a `.` instead of the second `:`: `nosetests tests\test_cli.py:AnalysisTestCase.test_bad_data_file`

It should be easy to catch it and print a more readable error message to the user, something like "Bad syntax: nosetests tests\test_cli.py:AnalysisTestCase:test_bad_data_file".
