### ISSUE TITLE
using nose+suds, AttributeError: 'NoneType' object has no attribute 'str'

### ISSUE THREAD

**Issue by yurui829** [nose-devs/nose#795]
Dear,

When I use nose framework to test webservice with suds, an error always occurs. Could you please help me?

See the error:

``` text
E
======================================================================
ERROR: testcases.testsoap.test_soap
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose-1.3.1-py2.7.egg\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "D:\workspase7\LearnNose\src\testcases\testsoap.py", line 12, in test_soap
    data = client.service.queryOrderAmount('222222')
  File "build\bdist.win32\egg\suds\client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "build\bdist.win32\egg\suds\client.py", line 595, in invoke
    soapenv = binding.get_message(self.method, args, kwargs)
  File "build\bdist.win32\egg\suds\bindings\binding.py", line 120, in get_message
    content = self.bodycontent(method, args, kwargs)
  File "build\bdist.win32\egg\suds\bindings\document.py", line 63, in bodycontent
    p = self.mkparam(method, pd, value)
  File "build\bdist.win32\egg\suds\bindings\document.py", line 105, in mkparam
    return Binding.mkparam(self, method, pdef, object)
  File "build\bdist.win32\egg\suds\bindings\binding.py", line 287, in mkparam
    return marshaller.process(content)
  File "build\bdist.win32\egg\suds\mx\core.py", line 62, in process
    self.append(document, content)
  File "build\bdist.win32\egg\suds\mx\core.py", line 73, in append
    log.debug('appending parent:\n%s\ncontent:\n%s', parent, content)
  File "C:\Python27\lib\logging\__init__.py", line 1122, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "C:\Python27\lib\logging\__init__.py", line 1252, in _log
    self.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 1262, in handle
    self.callHandlers(record)
  File "C:\Python27\lib\logging\__init__.py", line 1302, in callHandlers
    hdlr.handle(record)
  File "C:\Python27\lib\logging\__init__.py", line 744, in handle
    self.emit(record)
  File "C:\Python27\lib\site-packages\nose-1.3.1-py2.7.egg\nose\plugins\logcapture.py", line 82, in emit
    self.buffer.append(self.format(record))
  File "C:\Python27\lib\logging\__init__.py", line 719, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 464, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 328, in getMessage
    msg = msg % self.args
  File "build\bdist.win32\egg\suds\sax\document.py", line 58, in __str__
    return unicode(self).encode('utf-8')
  File "build\bdist.win32\egg\suds\sax\document.py", line 61, in __unicode__
    return self.str()
  File "build\bdist.win32\egg\suds\sax\document.py", line 48, in str
    s.append(self.root().str())
AttributeError: 'NoneType' object has no attribute 'str'
-------------------- >> begin captured logging << --------------------
suds.wsdl: DEBUG: reading wsdl at: http://xxx.xx.com/orderCalculationWebserviceForJson?wsdl ...
suds.cache: DEBUG: c:\users\admini~1\appdata\local\temp\suds\suds-1852635868-document.px expired, deleted
suds.transport.http: DEBUG: opening (http://xxx.xx.com/orderCalculationWebserviceForJson?wsdl)
suds.metrics: DEBUG: <?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="OrderCalculationWebs
```

The code is below:

``` python
import suds

def test_soap():
    uri = 'http://xxx.xx.com/orderCalculationWebserviceForJson?wsdl'
    client = suds.client.Client(uri)
    data = client.service.queryOrderAmount('222222')

    data = eval(data).get('code')
    assert data=='SUCCESS','call service fail.' 
```

all.cfg:

``` ini
[nosetests]
with-xunit=True
xunit-file=report/nosetests.xml
tests=src/testcases
```

``` text
>>nosetests -s -v -c conf\all.cfg
```

**Comment by radlws** [comment]
Just ran into the same issue, using suds 0.4, changing the logging info fixes it.  @yurui829 solution works, but its better to set the suds log level explicitly in your script i.e.

`
logging.getLogger('suds.client').setLevel(logging.ERROR)
logging.getLogger('suds.transport').setLevel(logging.ERROR)
logging.getLogger('suds.transport.http').setLevel(logging.INFO)  # Silent fail debug
logging.getLogger('suds.xsd.schema').setLevel(logging.ERROR)
logging.getLogger('suds.wsdl').setLevel(logging.ERROR)
logging.getLogger('suds.resolver').setLevel(logging.ERROR)
logging.getLogger('suds.xsd.query').setLevel(logging.ERROR)
logging.getLogger('suds.xsd.basic').setLevel(logging.ERROR)
logging.getLogger('suds.metrics').setLevel(logging.ERROR)
logging.getLogger('suds.mx.core').setLevel(logging.ERROR)
logging.getLogger('suds.xsd.sxbasic').setLevel(logging.ERROR)
logging.getLogger('suds.xsd.sxbase').setLevel(logging.ERROR)
logging.getLogger('suds.binding.marshaller').setLevel(logging.ERROR)
`

**Comment by jen-jackson** [comment]
Has anyone tried this updated version of document.py? Does it resolve the traceback as well? https://github.com/htj/suds-htj/tree/master/suds/sax
