### ISSUE TITLE
nosetest issue with profiling

### ISSUE THREAD

**Issue by abhirk** [nose-devs/nose#827]
I am on centos 6, python 2.6 and have nose==1.3.3 installed [with nose-timer and nose-cprof for timing and profiling]. I have an issue with profiling tests using nose, I get an exception each time I try to run it:

```
$ nosetests --verbose --nologcapture --processes=12 --process-timeout=180 --with-profile --profile-stats-file=/home/abhi/stats.dat --exe --testmatch="(?:^|[b./])[Tt]est" tests
Traceback (most recent call last):
  File "/home/abhi/env/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.3', 'console_scripts', 'nosetests')()
  File "/home/abhi/env/lib/python2.6/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib64/python2.6/unittest.py", line 816, in __init__
    self.runTests()
  File "/home/abhi/env/lib/python2.6/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/abhi/env/lib/python2.6/site-packages/nose/plugins/multiprocess.py", line 376, in run
    self.collect(test, testQueue, tasks, to_teardown, result)
  File "/home/abhi/env/lib/python2.6/site-packages/nose/plugins/multiprocess.py", line 321, in collect
    test_addr = self.addtask(testQueue,tasks,case)
  File "/home/abhi/env/lib/python2.6/site-packages/nose/plugins/multiprocess.py", line 536, in addtask
    test_addr = MultiProcessTestRunner.address(case)
  File "/home/abhi/env/lib/python2.6/site-packages/nose/plugins/multiprocess.py", line 551, in address
    raise Exception("Unable to convert %s to address" % case)
Exception: Unable to convert <function run_and_profile at 0x236b0c8> to address
 ```
 I might be wrong, but it seems that multiprocess doesn't play well with profiling, is this expected or a known issue? Just for testing I tried profiling using the nose-cprof module, [i.e. --with-cprofile --cprofile-stats-file switches] but had the same result. It is interesting to note that running the above with processes=1 gives the same result, whereas removing the --processes switch starts the test run fine (I guess the parallel testing is not disabled regardless of the number of processes. I did not finish the run  without --processes switch, since we have a large number of tests, will do so later this week)

Without profiling, the tests run fine, and the timer module also gives additional overview into test timings, but for further investigation into code bottlenecks, I need to profile the tests.

**Comment by abhirk** [comment]
Thanks. Closing issue.

**Comment by jakirkham** [comment]
Sorry to resurrect a dead issue. Is there a `--processes=0`, which would make sure that multiprocessing is disabled?

**Comment by parker-jana** [comment]
Looks like that's it:

http://nose.readthedocs.io/en/latest/usage.html#cmdoption--processes
