### ISSUE TITLE
ERROR: Failure: TypeError (type() takes 1 or 3 arguments)

### ISSUE THREAD

**Issue by robertodecurnex** [nose-devs/nose#836]
It's raising this error from `nose/case.py` 
This is happening 3 times every time I run my tests.
Another weird fact, it's adding 3 to the tests count

```
Ran 31 tests
```

When I have only 28.

```
======================================================================
ERROR: Failure: TypeError (type() takes 1 or 3 arguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/roberto/www/testsscheduler/nose-1.3.4-py2.7.egg/nose/loader.py", line 519, in makeTest
    return self._makeTest(obj, parent)
  File "/home/roberto/www/testsscheduler/nose-1.3.4-py2.7.egg/nose/loader.py", line 578, in _makeTest
    return MethodTestCase(obj)
  File "/home/roberto/www/testsscheduler/nose-1.3.4-py2.7.egg/nose/case.py", line 345, in __init__
    self.inst = self.cls()
TypeError: type() takes 1 or 3 arguments

----------------------------------------------------------------------
```

**Comment by vbraun** [comment]
I also tripped over this, and I had somewhere in my code a 

~~~~
class TestFoo(object):

    @classmethod
    def foo_test(cls):
        pass
~~~~

Maybe its a user error to ever use "test" as part of an identifier (though thats not trivial if you are switching to nose), but 

1. why are classes that don't derive from `unittest.TestCase` even looked at
1. better error message would be nice

**Comment by gnarea** [comment]
I'm not the author, but (1) is documented and I'm guessing the reason is that `nose` wants to encourage a different way to write test cases (using the stuff in `nose.tools`, for example), and (2) seems like a bug instead of something the author did consciously.

The real problem, I think, is that `nose` doesn't support tests that are class methods, which I find really inconvenient as it forces me to go for a suboptimal design in my tests by using instance methods.

**Comment by jszakmeister** [comment]
Yes, (1) is by design.  The idea was you didn't have to bring in unit test to do anything.  It also allowed a bit more flexibility too.  IIRC, tests derived from unittest.TestCase cannot have generator tests, while ones that don't can.

Let me ask some questions:

* How should class methods behave when it comes to tests?  `setUpClass()` and `tearDownClass()` are meant to only be called once for a class... but is that still the expectation when you have methods that are test methods that are class methods?

* Should we follow unittest's lead?  Unittest will still create an instance of the class, and still call the instance level setup and teardown around the test method.

* Who wants to chase down how things should work and patch nose to do it, along with some tests?

The fix could be as simple as this patch:

```diff
commit 6c176ab788952e6ad3cdeb97487be4c587eccdd3
Author: John Szakmeister <john@szakmeister.net>
Date:   Tue Dec 8 05:51:32 2015 -0500

    Allow @classmethods to be tests.
    
    Fixes #836.

diff --git a/nose/case.py b/nose/case.py
index c585c2b..092e885 100644
--- a/nose/case.py
+++ b/nose/case.py
@@ -8,7 +8,7 @@ import unittest
 from inspect import isfunction
 from nose.config import Config
 from nose.failure import Failure # for backwards compatibility
-from nose.util import resolve_name, test_address, try_run
+from nose.util import isclass, resolve_name, test_address, try_run
 
 log = logging.getLogger(__name__)
 
@@ -338,8 +338,12 @@ class MethodTestCase(TestBase):
         self.descriptor = descriptor
         if isfunction(method):
             raise ValueError("Unbound methods must be wrapped using pyversion.unbound_method before passing to MethodTestCase")
-        self.cls = method.im_class
+        if hasattr(method, 'im_self') and isclass(method.im_self):
+            self.cls = method.im_self
+        else:
+            self.cls = method.im_class
         self.inst = self.cls()
+
         if self.test is None:
             method_name = self.method.__name__
             self.test = getattr(self.inst, method_name)
```

But I'm really not sure without digging into it all and really making sure it's going to behave correctly in every case.  I simply don't have much bandwidth, and quite frankly, I want and need to spend that time elsewhere.
