### ISSUE TITLE
Nose import of setuptools can break other setup.py scripts

### ISSUE THREAD

**Issue by matthew-brett** [nose-devs/nose#867]
We ran into a problem with current nose and setuptools version 8, caused by the fact that nose imports setuptools.

With setuptools 8 (version installed by current virtualenv), this `setup.py` causes an error:

```
#!/usr/bin/env python
''' Installation script that breaks '''

from distutils.command import install
from distutils.core import setup

class installer(install.install):
    def run(self):
        import nose
        install.install.run(self)


setup(name='test',
      cmdclass = dict(install=installer)
     )
```

Running `python setup.py install` on this `setup.py` gives:

```
running install
running build
running install_egg_info
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    cmdclass = dict(install=installer)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 10, in run
    install.install.run(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
```

The setup.py script generates a distribution instance of type `distutils.dist.Distribution`. However, by the time the ``install`` command gets to its ``__init__`` method, setuptools has been imported by nose, which then monkeypatches distutils, so that when the code gets to this line in distutils (distutils/cmd.py line 59):

```
if not isinstance(dist, Distribution): 
```
the Distribution is now of type setuptools.dist.Distribution and isinstance is False, causing the error.

Is there any way of stopping nose importing setuptools from a default ``import nose``?   It can play havoc with setup.py scripts.

**Comment by matthew-brett** [comment]
Relevant Python bug report: http://bugs.python.org/issue23102
