### ISSUE TITLE
Importing nose changes import resolution order

### ISSUE THREAD

**Issue by montefra** [nose-devs/nose#877]
I'm build some tests for a package. As part of building them I'm temporary embedding a python interpreter in my code. I'm also trying to make 3D plots.

    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import axes3d
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

If I run the above code in a python or ipython console, everything works fine. Indeed inspecting the modules, I don't get any surprise:

    -> python2
    Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
    [GCC 4.9.1] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import matplotlib.pyplot as plt
    >>> plt
    <module 'matplotlib.pyplot' from '/home/xxx/.local/lib/python2.7/site-    packages/matplotlib/pyplot.pyc'>
    >>> import mpl_toolkits
    >>> mpl_toolkits
    <module 'mpl_toolkits' (built-in)>

Then I can create a 3d plot without problems.

But if I execute the code above anytime **after** importing `nose` I get the following error:
<pre>
Traceback (most recent call last):
  File "tests/test_iq_fit.py", line 14, in <module>
    ax = fig.add_subplot(111, projection='3d')
  File "/home/xxx/.local/lib/python2.7/site-packages/matplotlib/figure.py", line 958, in add_subplot
    a = subplot_class_factory(projection_class)(self, *args, **kwargs)
  File "/home/xxx/.local/lib/python2.7/site-packages/matplotlib/axes/_subplots.py", line 78, in __init__
    self._axes_class.__init__(self, fig, self.figbox, **kwargs)
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 91, in __init__
    *args, **kwargs)
  File "/home/xxx/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 436, in __init__
    self.cla()
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1045, in cla
    Axes.cla(self)
  File "/home/xxx/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 897, in cla
    self.grid(self._gridOn, which=rcParams['axes.grid.which'])
  File "/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.py", line 1256, in grid
    self._draw_grid = maxes._string_to_bool(b)
AttributeError: 'module' object has no attribute '_string_to_bool'
</pre>

If I inspect the modules I see that `matplotlib` is correctly imported, but now `mpl_toolkits` comes from a system-wide directory, containing an older version of the software, which causes the error.

    >>> import matplotlib.pyplot as plt
    >>> plt
    <module 'matplotlib.pyplot' from '/home/montefra/.local/lib/python2.7/site-packages/matplotlib/pyplot.pyc'>
    >>> import mpl_toolkits
    >>> mpl_toolkits
    <module 'mpl_toolkits' from '/usr/lib/pymodules/python2.7/mpl_toolkits/__init__.pyc'>

The `sys.path` in both cases is the same, except for the addition of the `tests` directory when running `nosetests`.

I'm under Kubuntu 14.10, with
nose==1.3.4
matplotlib==1.4.2
coverage==3.7.1

**Comment by montefra** [comment]
This is not nose fault. It happened to me a few more times outside nose tests, but never when using `ipython`.
I solved using virtual enviroments.
Sorry for bothering you
