### ISSUE TITLE
Nose multiprocess plugin doesn't work with coverage plugin

### ISSUE THREAD

**Issue by Ashald** [nose-devs/nose#892]
```
nosetests --processes=1 --process-restartworker --with-coverage --cover-erase --cover-xml --cover-html --cover-branches
Process Process-2:
Traceback (most recent call last):
  File "/opt/python-2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/python-2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/TeamCity/Agent2/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 652, in runner
    keyboardCaught, shouldStop, loaderClass, resultClass, config)
  File "/TeamCity/Agent2/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nose/plugins/multiprocess.py", line 669, in __runner
    config.plugins.begin()
  File "/TeamCity/Agent2/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/TeamCity/Agent2/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/TeamCity/Agent2/work/9171b2e0bb9e5275/.tox/py27-dj15/lib/python2.7/site-packages/nose/plugins/cover.py", line 156, in begin
    self.coverInstance.exclude('#pragma[: ]+[nN][oO] [cC][oO][vV][e
```

**Comment by Ashald** [comment]
Ah, sorry, it's duplicate. :(

**Comment by adib** [comment]
Pardon me but,

- This is a duplicate of which issue?
- What is the solution?
