### ISSUE TITLE
py 2.7 configparser import failure

### ISSUE THREAD

**Issue by mwjackson** [nose-devs/nose#897]
@jszakmeister Since the new release (about an hour ago), we are now seeing this:

Traceback (most recent call last):
  File "/vol/jenkins/jobs/LIVE_Smoke_Tests/workspace/.env/bin/nosetests", line 7, in <module>
    from nose import run_exit
  File "/vol/jenkins/jobs/LIVE_Smoke_Tests/workspace/.env/local/lib/python2.7/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/vol/jenkins/jobs/LIVE_Smoke_Tests/workspace/.env/local/lib/python2.7/site-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/vol/jenkins/jobs/LIVE_Smoke_Tests/workspace/.env/local/lib/python2.7/site-packages/nose/config.py", line 6, in <module>
    import configparser
ImportError: No module named configparser

What's up?

**Comment by jszakmeister** [comment]
You tell me. :-)  Is it really `import configparser` in the source?  It should be `import ConfigParser`.  I wonder if something with 2to3 went awry.

**Comment by jszakmeister** [comment]
Yep, that's what happened... I'm working on getting new wheels to PyPI.

**Comment by mwjackson** [comment]
Well we run virtualenv .env --clear before every build. Have hardcoded nose==1.3.4 in the meantime and all is green again, so I would assume its something in 1.3.5.

**Comment by mwjackson** [comment]
ok cool, thanks

**Comment by jszakmeister** [comment]
Okay, there's now a nose 1.3.6.  Sorry about that.  I have no idea why distutils and friends packaged the wrong source. :-(

**Comment by mwjackson** [comment]
thanks for the quick turnaround

**Comment by jszakmeister** [comment]
You're welcome, and thanks for letting me know!
