### ISSUE TITLE
Namespace test attributes

### ISSUE THREAD

**Issue by wolverdude** [nose-devs/nose#910]
My tests run fine with no flags, but when I use the `--failed` flag nose crashes.

```
ETraceback (most recent call last):
  File "/Users/me/.virtualenvs/myproject/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.4', 'console_scripts', 'nosetests')()
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/core.py", line 62, in run
    test(result)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/suite.py", line 224, in run
    test(orig)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/suite.py", line 224, in run
    test(orig)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/suite.py", line 224, in run
    test(orig)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 140, in run
    self.afterTest(result)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 64, in afterTest
    afterTest(self.test)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/proxy.py", line 111, in afterTest
    self.plugins.afterTest(self.test)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/plugins/testid.py", line 283, in afterTest
    key = str(self.tests[test.address()])
  File "/Users/me/.virtualenvs/myproject/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 93, in address
    return self.test.address()
TypeError: 'Address' object is not callable
```

It took me some debugging before I found this test class as the source of the problem:

```
import unittest
from mylib import Address

TestAddress(unittest.TestCase):
    
    def setUp(self):
        self.address = Address()

    def test_something(self):
        ...
```

It looks like there's a name conflict here, which I don't think should happen. Either `unittest` has an inherent `address` property that I'm not aware of or nose is modifying test objects. If nose modifies a test, it should prefix attributes so as to avoid such conflicts. Something like the classic `test._nose__address` would solve the problem nicely.

**Comment by jszakmeister** [comment]
> Something like the classic test._nose__address would solve the problem nicely.

Yes it would.  And changing it would also break things for plugins.  Unfortunately, it's hard to fix problems like this without breaking compatibility.

**Comment by leandrotoledo** [comment]
My commits before finding this issue:

```
2160ce7: This piece of code killed Travis somehow, investigating. 
6390b7f: Going deeper... 
fe06708: Trying to isolate the problem. 
4775107: Trying to isolate the problem. 
6cacea9: No clue what's going on with travis and Venue 
0d6b3a5: Seems like self.address conflicts with nose. Validating... 
```

If it can't be fixed without breaking backwards compatibility, can we provide a better traceback?
