### ISSUE TITLE
inspect.getargspec deprecated in python 3.5

### ISSUE THREAD

**Issue by njsmith** [nose-devs/nose#929]
We like to run tests with deprecation warnings turned into errors (`warnings.simplefilter("error", DeprecationWarning)`), to keep us honest. In the current 3.5 pre-releases, this causes failures inside `nose` itself, due to use of the deprecated `inspect.getargspec` function inside `nose.util.try_run`:
```
ERROR: test suite for <module 'test__datasource' from '/home/njs/src/numpy/build/testenv/lib/python3.5/site-packages/numpy/lib/tests/test__datasource.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/njs/src/cpython/b/install/lib/python3.5/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/njs/src/cpython/b/install/lib/python3.5/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/njs/src/cpython/b/install/lib/python3.5/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/njs/src/cpython/b/install/lib/python3.5/site-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
  File "/home/njs/src/cpython/b/install/lib/python3.5/inspect.py", line 1035, in getargspec
    stacklevel=2)
DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
```

Obviously we can put in a warnings filter to disable this (something like `warnings.filterwarnings("ignore", message="getargspec", category=DeprecationWarning, module="nose\\.")`), but thought you'd like to know.

**Comment by sciunto** [comment]
See #952 for a PR
