### ISSUE TITLE
Fails upon discovery or running with I don't know  what <... > is (<type 'FunctionWrapper'>)

### ISSUE THREAD

**Issue by yarikoptic** [nose-devs/nose#953]
FunctionWrapper comes from wrapt from a test wrapper with @vcr.use_cassette (vcr uses wrapt to provide decorators) for decorating few tests.  I have failed to isolate it to versions/envrionment  -- I thought I saw it with most fresh environment and old ones, but also often such a failure doesn't happen.  Now it started to occur in travis: see e.g. https://travis-ci.org/datalad/datalad/jobs/82226017 .  Here the full example trace-stack... any ideas/recommendations on how to avoid this nose crashing happening?
```
#7 datalad.crawler.nodes.tests.test_matches.test_a_href_match_pattern3 ... ok
ERROR
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/opt/python/2.7.9/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/core.py", line 62, in run
    test(result)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/opt/python/2.7.9/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 75, in run
    test(result)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 140, in run
    self.afterTest(result)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 64, in afterTest
    afterTest(self.test)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/proxy.py", line 111, in afterTest
    self.plugins.afterTest(self.test)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/plugins/testid.py", line 283, in afterTest
    key = str(self.tests[test.address()])
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 93, in address
    return self.test.address()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/case.py", line 253, in address
    return test_address(self.test)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/nose/util.py", line 436, in test_address
    raise TypeError("I don't know what %s is (%s)" % (test, t))
TypeError: I don't know what <function test_get_deposition_filename at 0x7f11fe176758> is (<type 'FunctionWrapper'>)
```

**Comment by jszakmeister** [comment]
Why is this a nose problem?  It looks to me like something (a plugin, something else?) is wrapping up a function in a way that test_address can't discern what it is.  The short form: nose can't determine where test_get_deposition_filename lives because it's wrapped in an object that doesn't look like anything Nose knows about.

I'd figure out where FunctionWrapper actually comes from and teach it to more properly wrap the test function.  You'll find the implementation of test_address in nose/util.py.  It's quite long, and quite thorough, but hopefully it'll help you determine what is wrong.

**Comment by yarikoptic** [comment]
Thanks @jszakmeister , indeed I should look into complaining to wrapt folks and I am not sure how I have managed to not note the obvious now --failed culprit! Thanks!

But as for "Why is this a nose problem?" -- I guess it is beccause noseid plugin shipped with the nose and apparently it (or nose) not robust to such cases when nose has no difficulty finding/running it:

```
$> venv-tests/bin/nosetests -s -v datalad.crawler.nodes.tests.test_misc:test_get_deposition_filename 
datalad.crawler.nodes.tests.test_misc.test_get_deposition_filename ... ok

----------------------------------------------------------------------
Ran 1 test in 0.127s

OK

$> venv-tests/bin/nosetests -s -v --failed datalad.crawler.nodes.tests.test_misc:test_get_deposition_filename 
ERROR
Traceback (most recent call last):
  File "venv-tests/bin/nosetests", line 11, in <module>
    sys.exit(run_exit())
  File "/home/yoh/proj/datalad/datalad/venv-tests/local/lib/python2.7/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/yoh/proj/datalad/datalad/venv-tests/local/lib/python2.7/site-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.r
...
```

**Comment by jszakmeister** [comment]
> But as for "Why is this a nose problem?" -- I guess it is because noseid plugin shipped with the nose and apparently it (or nose) not robust to such cases when nose has no difficulty finding/running it:

Well, I guess you could say that, but then I'll ask the question that's lingering behind here: if Nose cannot figure out what it is running, then how is it going to let you run that test individually?  What should the failure mode be and how is that going to work?  I think when you start digging deeper into it, you're going to find that some things need to be present and one of them will be knowing how to reference that test.  If test_address() can be made to adapt, great.  But if not, it's no simple change to make it "more robust".

**Comment by yarikoptic** [comment]
well, e.g. here would be my cruel fix to address this issue that decorator might be a callable object (not a function per se):
```
--- /home/yoh/proj/datalad/datalad/venv-tests/local/lib/python2.7/site-packages/nose/util.py.orig	2015-09-29 07:23:51.127417008 -0700
+++ /home/yoh/proj/datalad/datalad/venv-tests/local/lib/python2.7/site-packages/nose/util.py	2015-09-29 07:26:02.709523646 -0700
@@ -400,7 +400,7 @@
         file = getattr(test, '__file__', None)
         module = getattr(test, '__name__', None)
         return (src(file), module, call)
-    if t == types.FunctionType or issubclass(t, type) or t == types.ClassType:
+    if t == types.FunctionType or issubclass(t, type) or t == types.ClassType or (isinstance(t, object) and hasattr(test, '__call__')):
         module = getattr(test, '__module__', None)
         if module is not None:
             m = sys.modules[module]
```

not sure of that isinstance(t, object) ;-)

**Comment by jszakmeister** [comment]
> well, e.g. here would be my cruel fix to address this issue that decorator might be a callable object (not a function per se):

It looks like wrapt deviated quite a bit from the norm here.  FunctionWrapper doesn't appear to be like any other class I've ever seen--and behaves rather oddly.  Unfortunately, the fix above breaks other cases.  I think there's another way to make it work though.  If we move the check near the end, I think we can check for callable() there and try to pick it apart.

**Comment by yarikoptic** [comment]
cool, whatever works is good with me ;-) thanks

**Comment by jszakmeister** [comment]
@yarikoptic Can you try this patch:

```diff
diff --git a/nose/util.py b/nose/util.py
index bfe1658..44b507f 100644
--- a/nose/util.py
+++ b/nose/util.py
@@ -392,6 +392,17 @@ def test_address(test):
     """
     if hasattr(test, "address"):
         return test.address()
+
+    def _address_from_module_file_name(test):
+        module = getattr(test, '__module__', None)
+        if module is not None:
+            m = sys.modules[module]
+            file = getattr(m, '__file__', None)
+            if file is not None:
+                file = os.path.abspath(file)
+        call = getattr(test, '__name__', None)
+        return (src(file), module, call)
+
     # type-based polymorphism sucks in general, but I believe is
     # appropriate here
     t = type(test)
@@ -401,14 +412,7 @@ def test_address(test):
         module = getattr(test, '__name__', None)
         return (src(file), module, call)
     if t == types.FunctionType or issubclass(t, type) or t == types.ClassType:
-        module = getattr(test, '__module__', None)
-        if module is not None:
-            m = sys.modules[module]
-            file = getattr(m, '__file__', None)
-            if file is not None:
-                file = os.path.abspath(file)
-        call = getattr(test, '__name__', None)
-        return (src(file), module, call)
+        return _address_from_module_file_name(test)
     if t == types.MethodType:
         cls_adr = test_address(test.im_class)
         return (src(cls_adr[0]), cls_adr[1],
@@ -431,6 +435,13 @@ def test_address(test):
             method_name = test._testMethodName
         return (src(cls_adr[0]), cls_adr[1],
                 "%s.%s" % (cls_adr[2], method_name))
+
+    # As a last resort, check callable.  This like wrapt create custom types
+    # that Nose doesn't recognize, but behave like callables.  So let's attempt
+    # to generate an address using the same approach we do for functions.
+    if callable(test):
+        return _address_from_module_file_name(test)
+
     if (hasattr(test, '__class__') and
             test.__class__.__module__ not in ('__builtin__', 'builtins')):
         return test_address(test.__class__)
```

**Comment by jszakmeister** [comment]
ping

**Comment by yarikoptic** [comment]
Ah sorry, have missed your reply... I will try later today. Thanks

**Comment by yarikoptic** [comment]
damn... I feel silly but I can't reproduce it now and can't remember if I haven't done some persistent workaround (and I did try previous code states).
