### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'getargspec' on Python 3.6 (nightly)

### ISSUE THREAD

**Issue by ogrisel** [nose-devs/nose#976]
When running numpy tests with nosetests 1.3.7 under Python 3.6 (freshly built from the development branch), I get:

```
======================================================================
ERROR: test suite for <module 'test_array_from_pyobj' from '/opt/lib/python3.6/site-packages/numpy/f2py/tests/test_array_from_pyobj.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/opt/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/opt/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/opt/lib/python3.6/site-packages/nose/util.py", line 453, in try_run
    inspect.getargspec(func)
AttributeError: module 'inspect' has no attribute 'getargspec'
```

because `getargspec` has been deprecated in Python 3.5 and removed in the Python development branch (leading to 3.6).

Instead the `Signature` class should be used:

https://docs.python.org/3/library/inspect.html#introspecting-callables-with-the-signature-object

**Comment by JonathonReinhart** [comment]
:+1: I'm also seeing this: https://travis-ci.org/JonathonReinhart/scuba/jobs/103024601

**Comment by JonathonReinhart** [comment]
It looks like [`inspect.getargspec`](https://docs.python.org/3/library/inspect.html#inspect.getargspec) is deprecated:
> *Deprecated since version 3.0:* Use [signature()](https://docs.python.org/3/library/inspect.html#inspect.signature) and [Signature Object](https://docs.python.org/3/library/inspect.html#inspect-signature-object), which provide a better introspecting API for callables.

[Those APIs](https://docs.python.org/3/library/inspect.html#introspecting-callables-with-the-signature-object) appear to have been added in 3.3.  (I'm not sure what they wanted you to use from 3.0 to 3.3 though!)

**Comment by jszakmeister** [comment]
I would love to say that I'm going to fix this, but starting at the beginning of this year, Nose is effectively un-maintained (I put out a [notice](https://groups.google.com/forum/#!topic/nose-dev/rkofU1WdNNc) back in October about my intentions and *no one* has attempted to step up as maintainer).

I hope to cut a new release with the current fixes that are on master, but I don't plan on spending any time on Nose beyond that.  Sorry.

**Comment by JonathonReinhart** [comment]
I'd never even heard of Nose2 until I looked at the [nose-devs](https://github.com/nose-devs) group. It seems as if Nose is simply too popular as-is?

I planned on taking a look at this issue to see if it could be fixed in a minimally invasive way. I see that #952 tries to add Python 3.6 compatibility. If that were passing, would you be interested in merging?  I wish I could say I'd have time to maintain Nose, but I don't think that would be possible for me right now.

**Comment by jszakmeister** [comment]
> If that were passing, would you be interested in merging?

I wish I could say yes, but I've found that I really have to sit down and work through every pull request I merge.  It's simply become too much of a time investment, especially since the code base is so fragile. :-(  You might be able to convince me to do it, but I think it's a stretch.  Someone else tried to adjust the doctest failures, but that failure also uncovers the fact that names are far different--so simply changing the doctests to allow the new names isn't really the right answer, IMHO.  It seems like a problem that needs fixing, and again, I don't have bandwidth to do it (which is why I'm stepping down).
